<?php

define('SELECTBOX_DROPDOWN_FIELD_DIR', basename(dirname(__FILE__)));
define('SELECTBOX_DROPDOWN_FIELD_JAVASCRIPT', SELECTBOX_DROPDOWN_FIELD_DIR.'/javascript/');
define('SELECTBOX_DROPDOWN_FIELD_DIR_THIRD_PARTY_DIR', SELECTBOX_DROPDOWN_FIELD_JAVASCRIPT.'thirdparty/');